modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/SlimeKnights/TinkersConstruct/issues"
logoFile="logo.png"

[[mods]]
    modId="tconstruct"
    version="3.0.1.DEV.f1f2d41"
    displayName="Tinkers' Construct"
    authors="Slime Knights"
    description='''
A little of this, a little of that, a lot of tinkering, and a lot of tools
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-construct"
    [[dependencies.mantle]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"