blank_issues_enabled: false
contact_links:
 - name: SlimeKnights Discord
   url: https://discord.gg/njGrvuh
   about: Join our discord to duscuss new features or to discuss things that may not be a bug.
